<div class="container">
    <main class="site-content">
        <section class="projects">
            <h2>Your Projects</h2>
        </section>

        <section class="trending">
            <h2>Trending</h2>
            <ul>
                <li>
                    <img class="profile-img" src="img/user-profile.png" alt="" />
                    <div class="profile-info">
                        <h3 class="profile-username">@tegan</h3>
                        <p class="profile-desc">World Peace Builder</p>
                    </div>
                </li>
                <li>
                    <img class="profile-img" src="img/user-profile.png" alt="" />
                    <div class="profile-info">
                        <h3 class="profile-username">@morgan</h3>
                        <p class="profile-desc">Super Cool Project</p>
                    </div>
                </li>
                <li>
                    <img class="profile-img" src="img/user-profile.png" alt="" />
                    <div class="profile-info">
                        <h3 class="profile-username">@kendall</h3>
                        <p class="profile-desc">Life Changing App</p>
                    </div>
                </li>
                <li>
                    <img class="profile-img" src="img/user-profile.png" alt="" />
                    <div class="profile-info">
                        <h3 class="profile-username">@alex</h3>
                        <p class="profile-desc">No Traffic Maker</p>
                    </div>
                </li>
            </ul>
        </section>
    </main>
</div>
